-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 11:18:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`Autors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`Autors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Pseudo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`Posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Content` VARCHAR(150) NULL,
  `DateEntry` DATE NULL,
  `DateExit` DATE NULL,
  `degree` INT NULL,
  `Autors_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Posts_Autors1_idx` (`Autors_id` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_Autors1`
    FOREIGN KEY (`Autors_id`)
    REFERENCES `blog`.`Autors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`Categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`Posts_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`Posts_Categories` (
  `Posts_idPosts` INT UNSIGNED NOT NULL,
  `Categories_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Posts_idPosts`, `Categories_id`),
  INDEX `fk_Posts_has_Categories_Categories1_idx` (`Categories_id` ASC) VISIBLE,
  INDEX `fk_Posts_has_Categories_Posts_idx` (`Posts_idPosts` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_has_Categories_Posts`
    FOREIGN KEY (`Posts_idPosts`)
    REFERENCES `blog`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_has_Categories_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `blog`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`Commentaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`Commentaries` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Content` MEDIUMTEXT NULL,
  `Date` DATE NULL,
  `Posts_id` INT UNSIGNED NOT NULL,
  `Autors_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Commentaries_Posts1_idx` (`Posts_id` ASC) VISIBLE,
  INDEX `fk_Commentaries_Autors1_idx` (`Autors_id` ASC) VISIBLE,
  CONSTRAINT `fk_Commentaries_Posts1`
    FOREIGN KEY (`Posts_id`)
    REFERENCES `blog`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaries_Autors1`
    FOREIGN KEY (`Autors_id`)
    REFERENCES `blog`.`Autors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
